In [2]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [3]:
def print_tensor_details(tensor):
    print(f"tensor={tensor}")
    print(f"size or tensor ={len(tensor)}")
    print (f" number of dimensions in tensor={tensor.ndim}")
    print(f" shape of tension {tensor.shape}") 
    print(f" data type of every element ={tensor.dtype}")

In [4]:
array=np.array([10,20,30,40,50,60])
tensor_1d=tf.constant(array)
print_tensor_details(tensor_1d)

tensor=[10 20 30 40 50 60]
size or tensor =6
 number of dimensions in tensor=1
 shape of tension (6,)
 data type of every element =<dtype: 'int64'>

In [5]:
# create a data frame (2d array) using pandas
df = pd.DataFrame({
    "feature1": [10, 20, 30, 40, 50],
    "feature2": [60, 70, 80, 90, 100]
})
df

   feature1  feature2
0        10        60
1        20        70
2        30        80
3        40        90
4        50       100

In [7]:
tensor_2d=tf.constant(df)
print_tensor_details(tensor_2d)

tensor=[[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]
size or tensor =5
 number of dimensions in tensor=2
 shape of tension (5, 2)
 data type of every element =<dtype: 'int64'>

In [9]:
df =pd.read_csv("./Salary_Data.csv")
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [10]:
tensor_2d=tf.constant(df)
print_tensor_details(tensor_2d)

tensor=[[1.10000e+00 3.93430e+04]
 [1.30000e+00 4.62050e+04]
 [1.50000e+00 3.77310e+04]
 [2.00000e+00 4.35250e+04]
 [2.20000e+00 3.98910e+04]
 [2.90000e+00 5.66420e+04]
 [3.00000e+00 6.01500e+04]
 [3.20000e+00 5.44450e+04]
 [3.20000e+00 6.44450e+04]
 [3.70000e+00 5.71890e+04]
 [3.90000e+00 6.32180e+04]
 [4.00000e+00 5.57940e+04]
 [4.00000e+00 5.69570e+04]
 [4.10000e+00 5.70810e+04]
 [4.50000e+00 6.11110e+04]
 [4.90000e+00 6.79380e+04]
 [5.10000e+00 6.60290e+04]
 [5.30000e+00 8.30880e+04]
 [5.90000e+00 8.13630e+04]
 [6.00000e+00 9.39400e+04]
 [6.80000e+00 9.17380e+04]
 [7.10000e+00 9.82730e+04]
 [7.90000e+00 1.01302e+05]
 [8.20000e+00 1.13812e+05]
 [8.70000e+00 1.09431e+05]
 [9.00000e+00 1.05582e+05]
 [9.50000e+00 1.16969e+05]
 [9.60000e+00 1.12635e+05]
 [1.03000e+01 1.22391e+05]
 [1.05000e+01 1.21872e+05]
 [1.10000e+01 1.40000e+05]
 [1.20000e+01 1.55000e+05]
 [1.30000e+01 1.56000e+05]]
size or tensor =33
 number of dimensions in tensor=2
 shape of tension (33, 2)
 data type of every element =<dtype: 'float64'>